services:
  web:
    container_name: web-laravel_vue
    build:
      context: ./docker/nginx/
    ports:
      - "8080:443"
    volumes:
      - ./docker/nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf
      - ./src:/var/www/html
      - ssl_volume:/etc/nginx/ssl
    depends_on:
      - app
      - db

  app:
    container_name: app-laravel_vue
    build:
      context: ./docker/app/
    ports:
      - "5173:5173" # Viteのポート
    volumes:
      - ./src:/var/www/html/
      - ./docker/app/www.conf:/etc/php-fpm.d/www.conf
      - ./docker/app/php.ini:/etc/php.ini
      - node_modules_volume:/var/www/html/node_modules
      - ssl_volume:/etc/nginx/ssl
    deploy:
      resources:
        limits:
          cpus: "0.5"

  db:
    container_name: pgdb-laravel_vue
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
      - pgdb-laravel_vue-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cheerpay
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel

  db-testing:
    container_name: pgdb-laravel_vue_test
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
      - pgdb-laravel_vue_test-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cheerpay_test
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel

  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  minio:
    image: quay.io/minio/minio:latest
    container_name: s3-minio
    environment:
      MINIO_ROOT_USER: admin123
      MINIO_ROOT_PASSWORD: admin123
    command: server --console-address ":9090" /data
    volumes:
      - ./minio/data:/data
    ports:
      - 9000:9000
      - 9090:9090

volumes:
  pgdb-laravel_vue-volume:
  pgdb-laravel_vue_test-volume:
  node_modules_volume:
  ssl_volume:
