/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id"
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key"
        },
        {
            "name": "tags"
        }
    ],
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "api.staff.chatgpt.get": [
        {
            "name": "staffId"
        },
        {
            "name": "promptId"
        }
    ],
    "api.tips.chatgpt.get": [
        {
            "name": "tipId"
        },
        {
            "name": "promptId"
        }
    ],
    "zipcloud": [
        {
            "name": "zipCode"
        }
    ],
    "api.staff.update.profile.image": [],
    "api.staff.delete.profile.image": [],
    "api.staff.update.message.notified": [],
    "api.business-operator.create-staff": [],
    "api.business-operator.delete-file": [],
    "api.business-operator.create-business-operator": [],
    "api.business-operator.payment-advice-pdf": [],
    "api.business-operator.staff.index": [],
    "api.business-operator.staff.admin-staff.delete": [
        {
            "name": "adminStaffId"
        }
    ],
    "api.business-operator.staff.delete": [
        {
            "name": "staffId"
        }
    ],
    "api.business-operator.staff.update.profile.image": [
        {
            "name": "staffId"
        }
    ],
    "api.business-operator.staff.delete.profile.image": [
        {
            "name": "staffId"
        }
    ],
    "api.business-operator.staff.update.message.notified": [
        {
            "name": "staffId"
        }
    ],
    "api.business-operator.staff.schedules": [
        {
            "name": "staffId"
        }
    ],
    "api.business-operator.staff.update.schedules": [
        {
            "name": "staffId"
        }
    ],
    "api.business-operator.setting.update.publish": [],
    "api.business-operator.setting.update.review-publish": [],
    "api.business-operator.setting.update.staff-ranking-publish": [],
    "api.business-operator.profile.update.image": [],
    "api.business-operator.profile.delete.image": [],
    "api.corporation.payment-advice-pdf": [],
    "api.corporation.update.publish": [],
    "user.update.profile.image": [],
    "user.update.profile.show.setting": [],
    "user.api.business-operator.delete-review": [
        {
            "name": "businessId"
        },
        {
            "name": "reviewId"
        }
    ],
    "user.api.staff.toggle-favorite": [
        {
            "name": "staffId"
        }
    ],
    "user.api.staff.user-like": [
        {
            "name": "staffId"
        }
    ],
    "user.api.payment-info.create-payment-intent": [],
    "user.api.payment-info.get-setup-intent": [],
    "user.guest.exists": [
        {
            "name": "businessId"
        },
        {
            "name": "staffId"
        }
    ],
    "user.guest.create-payment-intent": [
        {
            "name": "businessId"
        },
        {
            "name": "staffId"
        }
    ],
    "welcome": [],
    "owner": [],
    "faq": [],
    "privacy": [],
    "law": [],
    "term": [],
    "revuew-guide-line": [],
    "upload.get": [],
    "upload.post": [],
    "stripe.webhook": [],
    "user.guest.logout": [],
    "user.guest.mypage.index": [],
    "user.guest.business-operator.index": [],
    "user.guest.business-operator.show": [
        {
            "name": "businessId"
        }
    ],
    "user.guest.business-operator.create-review": [
        {
            "name": "businessId"
        }
    ],
    "user.guest.business-operator.store-review": [
        {
            "name": "businessId"
        }
    ],
    "user.guest.business-operator.staff.index": [
        {
            "name": "businessId"
        }
    ],
    "user.guest.business-operator.staff.show": [
        {
            "name": "businessId"
        },
        {
            "name": "staffId"
        }
    ],
    "user.guest.business-operator.staff.userTip.payment": [
        {
            "name": "businessId"
        },
        {
            "name": "staffId"
        }
    ],
    "user.guest.business-operator.staff.userTip.payment.complete": [
        {
            "name": "businessId"
        },
        {
            "name": "staffId"
        }
    ],
    "user.guest.notification.index": [],
    "user.guest.notification.show": [
        {
            "name": "notificationId"
        }
    ],
    "user.guest.notification.show.private": [
        {
            "name": "notificationId"
        }
    ],
    "user.guest.notification.pdf": [
        {
            "name": "notificationId"
        }
    ],
    "user.change-email.check": [],
    "user.change-email.complete": [],
    "user.sns-login": [],
    "user.sns-logout": [],
    "user.callback": [],
    "user.signup": [],
    "user.login-method": [],
    "user.register": [],
    "user.": [],
    "user.login": [],
    "user.guest-login": [],
    "user.password.request": [],
    "user.password.email": [],
    "user.password.reset": [
        {
            "name": "token"
        }
    ],
    "user.password.store": [],
    "user.verification.notice": [],
    "user.verification.verify": [
        {
            "name": "id"
        },
        {
            "name": "hash"
        }
    ],
    "user.verification.send": [],
    "user.password.confirm": [],
    "user.password.update": [],
    "user.logout": [],
    "user.profile.show": [],
    "user.profile.update": [],
    "user.profile.destroy": [],
    "user.mypage.index": [],
    "user.profile.setting.show": [],
    "user.profile.change-email.show": [],
    "user.profile.change-email.create": [],
    "user.profile.change-password.show": [],
    "user.profile.change-password.update": [],
    "user.payment-info.show": [],
    "user.payment-info.create": [],
    "user.payment-info.confirm": [],
    "user.payment-info.register": [],
    "user.payment-info.delete": [],
    "user.notification.index": [],
    "user.notification.show": [
        {
            "name": "notificationId"
        }
    ],
    "user.notification.show.private": [
        {
            "name": "notificationId"
        }
    ],
    "user.notification.pdf": [
        {
            "name": "notificationId"
        }
    ],
    "user.business-operator.index": [],
    "user.business-operator.show": [
        {
            "name": "businessId"
        }
    ],
    "user.business-operator.create-review": [
        {
            "name": "businessId"
        }
    ],
    "user.business-operator.store-review": [
        {
            "name": "businessId"
        }
    ],
    "user.business-operator.staff.index": [
        {
            "name": "businessId"
        }
    ],
    "user.business-operator.staff.show": [
        {
            "name": "businessId"
        },
        {
            "name": "staffId"
        }
    ],
    "user.business-operator.staff.userTip.store": [
        {
            "name": "businessId"
        },
        {
            "name": "staffId"
        }
    ],
    "user.pointHistory.index": [],
    "user.pointHistory.point.index": [],
    "user.pointHistory.expired.index": [],
    "user.tips.index": [],
    "user.tips.show": [
        {
            "name": "tipId"
        }
    ],
    "user.favorite-staff.index": [],
    "user.point-charge.index": [],
    "user.point-charge.payment-select": [],
    "user.point-charge.payment-complete": [],
    "user.point-charge.payment-complete-exist-card": [],
    "user.point-charge.handle-get-payment-select": [],
    "user.point-charge.handle-get-payment-complete": [],
    "user.cancel.index": [],
    "user.cancel.confirm": [],
    "user.cancel.delete": [],
    "mits-admin.login": [],
    "mits-admin.": [],
    "mits-admin.logout": [],
    "mits-admin.dashboard": [],
    "mits-admin.business-operator.index": [],
    "mits-admin.business-operator.create": [],
    "mits-admin.business-operator.store": [],
    "mits-admin.business-operator.show": [
        {
            "name": "businessId"
        }
    ],
    "mits-admin.business-operator.update": [
        {
            "name": "businessId"
        }
    ],
    "mits-admin.business-operator.delete": [
        {
            "name": "businessId"
        }
    ],
    "mits-admin.business-operator.destroy": [
        {
            "name": "businessId"
        }
    ],
    "mits-admin.business-operator.review.index": [
        {
            "name": "businessId"
        }
    ],
    "mits-admin.business-operator.review.destroy": [
        {
            "name": "businessId"
        },
        {
            "name": "reviewId"
        }
    ],
    "mits-admin.business-operator.review.show": [
        {
            "name": "businessId"
        },
        {
            "name": "reviewId"
        }
    ],
    "mits-admin.corporation.index": [],
    "mits-admin.corporation.create": [],
    "mits-admin.corporation.store": [],
    "mits-admin.corporation.show": [
        {
            "name": "corporationId"
        }
    ],
    "mits-admin.corporation.update": [
        {
            "name": "corporationId"
        }
    ],
    "mits-admin.corporation.delete": [
        {
            "name": "corporationId"
        }
    ],
    "mits-admin.corporation.destroy": [
        {
            "name": "corporationId"
        }
    ],
    "mits-admin.staff-ranking": [
        {
            "name": "yearDate"
        }
    ],
    "mits-admin.user-ranking": [
        {
            "name": "yearDate"
        }
    ],
    "admin-staff.register": [],
    "admin-staff.": [],
    "admin-staff.login": [],
    "admin-staff.password.request": [],
    "admin-staff.password.email": [],
    "admin-staff.password.reset": [
        {
            "name": "token"
        }
    ],
    "admin-staff.password.store": [],
    "admin-staff.mypage.index": [],
    "admin-staff.tips.index": [],
    "admin-staff.tips.show": [
        {
            "name": "tipId"
        }
    ],
    "admin-staff.tips.create": [
        {
            "name": "tipId"
        }
    ],
    "admin-staff.tips.delete": [
        {
            "name": "tipId"
        },
        {
            "name": "replyId"
        }
    ],
    "admin-staff.logout": [],
    "staff.change-email.check": [],
    "staff.change-email.complete": [],
    "staff.register": [],
    "staff.create": [],
    "staff.login": [],
    "staff.": [],
    "staff.password.request": [],
    "staff.password.email": [],
    "staff.password.reset": [
        {
            "name": "token"
        }
    ],
    "staff.password.store": [],
    "staff.mypage.index": [],
    "staff.profile.show": [],
    "staff.profile.update": [],
    "staff.profile.change-email.show": [],
    "staff.profile.change-email.create": [],
    "staff.profile.change-password.show": [],
    "staff.profile.change-password.update": [],
    "staff.profile.show.setting": [],
    "staff.notification.index": [],
    "staff.notification.show": [
        {
            "name": "notificationId"
        }
    ],
    "staff.notification.show.private": [
        {
            "name": "notificationId"
        }
    ],
    "staff.notification.pdf": [
        {
            "name": "notificationId"
        }
    ],
    "staff.like.index": [],
    "staff.pointHistory.index": [],
    "staff.tips.index": [],
    "staff.tips.show": [
        {
            "name": "tipId"
        }
    ],
    "staff.tips.create": [
        {
            "name": "tipId"
        }
    ],
    "staff.tips.delete": [
        {
            "name": "tipId"
        },
        {
            "name": "replyId"
        }
    ],
    "staff.logout": [],
    "business-operator.change-email.check": [],
    "business-operator.change-email.complete": [],
    "business-operator.register": [],
    "business-operator.": [],
    "business-operator.login": [],
    "business-operator.password.request": [],
    "business-operator.password.email": [],
    "business-operator.password.reset": [
        {
            "name": "token"
        }
    ],
    "business-operator.password.store": [],
    "business-operator.mypage.index": [],
    "business-operator.notification.index": [],
    "business-operator.notification.show": [
        {
            "name": "notificationId"
        }
    ],
    "business-operator.notification.show.private": [
        {
            "name": "notificationId"
        }
    ],
    "business-operator.notification.pdf": [
        {
            "name": "notificationId"
        }
    ],
    "business-operator.profile.edit": [],
    "business-operator.profile.update": [],
    "business-operator.profile.change-email.show": [],
    "business-operator.profile.change-email.create": [],
    "business-operator.profile.change-password.show": [],
    "business-operator.profile.change-password.update": [],
    "business-operator.staff.select": [],
    "business-operator.staff.index": [],
    "business-operator.staff.schedules.index": [],
    "business-operator.staff.tips.index": [],
    "business-operator.staff.tips.show": [
        {
            "name": "tipId"
        }
    ],
    "business-operator.staff.tips.create": [
        {
            "name": "tipId"
        }
    ],
    "business-operator.staff.tips.delete": [
        {
            "name": "tipId"
        },
        {
            "name": "replyId"
        }
    ],
    "business-operator.staff.admin.index": [],
    "business-operator.staff.admin.add.show": [],
    "business-operator.staff.admin.add.create": [],
    "business-operator.staff.admin.show": [
        {
            "name": "adminStaffId"
        }
    ],
    "business-operator.staff.admin.update": [
        {
            "name": "adminStaffId"
        }
    ],
    "business-operator.staff.admin.change-email.show": [
        {
            "name": "adminStaffId"
        }
    ],
    "business-operator.staff.admin.change-email.update": [
        {
            "name": "adminStaffId"
        }
    ],
    "business-operator.staff.add.show": [],
    "business-operator.staff.add.create": [],
    "business-operator.staff.show": [
        {
            "name": "staffId"
        }
    ],
    "business-operator.staff.update": [
        {
            "name": "staffId"
        }
    ],
    "business-operator.staff.setting.show": [
        {
            "name": "staffId"
        }
    ],
    "business-operator.staff.point-history.index": [
        {
            "name": "staffId"
        }
    ],
    "business-operator.staff.change-email.show": [
        {
            "name": "staffId"
        }
    ],
    "business-operator.staff.change-email.update": [
        {
            "name": "staffId"
        }
    ],
    "business-operator.transfer.select": [],
    "business-operator.transfer.application": [],
    "business-operator.transfer.application.update": [
        {
            "name": "settingId"
        }
    ],
    "business-operator.transfer.bank-account": [],
    "business-operator.transfer.bank-account.update": [],
    "business-operator.transfer.payment-advice": [],
    "business-operator.qr.index": [],
    "business-operator.qr.business-operator": [],
    "business-operator.qr.staff": [],
    "business-operator.setting.index": [],
    "business-operator.setting.publish": [],
    "business-operator.setting.review-publish": [],
    "business-operator.setting.staff-ranking-publish": [],
    "business-operator.setting.tip": [],
    "business-operator.setting.tip.update": [],
    "business-operator.point.index": [],
    "business-operator.point.staff": [
        {
            "name": "yearMonth"
        }
    ],
    "business-operator.review.index": [],
    "business-operator.review.delete": [],
    "business-operator.deposit-details.index": [],
    "business-operator.deposit-details.staff": [
        {
            "name": "requestId"
        }
    ],
    "business-operator.media-check.index": [],
    "business-operator.media-check.delete": [],
    "business-operator.cancel.index": [],
    "business-operator.cancel.confirm": [],
    "business-operator.cancel.delete": [],
    "business-operator.dashboard": [],
    "business-operator.verification.notice": [],
    "business-operator.verification.verify": [
        {
            "name": "id"
        },
        {
            "name": "hash"
        }
    ],
    "business-operator.verification.send": [],
    "business-operator.password.confirm": [],
    "business-operator.password.update": [],
    "business-operator.logout": [],
    "corporation.change-email.check": [],
    "corporation.change-email.complete": [],
    "corporation.register": [],
    "corporation.": [],
    "corporation.login": [],
    "corporation.password.request": [],
    "corporation.password.email": [],
    "corporation.password.reset": [
        {
            "name": "token"
        }
    ],
    "corporation.password.store": [],
    "corporation.verification.notice": [],
    "corporation.verification.verify": [
        {
            "name": "id"
        },
        {
            "name": "hash"
        }
    ],
    "corporation.verification.send": [],
    "corporation.password.confirm": [],
    "corporation.password.update": [],
    "corporation.logout": [],
    "corporation.dashboard": [],
    "corporation.mypage.index": [],
    "corporation.profile.edit": [],
    "corporation.profile.change-email.show": [],
    "corporation.profile.change-email.create": [],
    "corporation.profile.change-password.show": [],
    "corporation.profile.change-password.update": [],
    "corporation.notification.index": [],
    "corporation.notification.show": [
        {
            "name": "notificationId"
        }
    ],
    "corporation.notification.show.private": [
        {
            "name": "notificationId"
        }
    ],
    "corporation.notification.pdf": [
        {
            "name": "notificationId"
        }
    ],
    "corporation.transfer.select": [],
    "corporation.transfer.application": [],
    "corporation.transfer.application.update": [
        {
            "name": "settingId"
        }
    ],
    "corporation.transfer.bank-account": [],
    "corporation.transfer.bank-account.update": [],
    "corporation.transfer.payment-advice": [],
    "corporation.setting.index": [],
    "corporation.setting.publish": [],
    "corporation.point.index": [],
    "corporation.point.business-operator": [
        {
            "name": "yearMonth"
        }
    ],
    "corporation.point.staff": [
        {
            "name": "yearMonth"
        },
        {
            "name": "businessId"
        }
    ],
    "corporation.business-operator.index": [],
    "corporation.business-operator.management.index": [],
    "corporation.business-operator.management.create": [],
    "corporation.business-operator.management.confirm": [],
    "corporation.business-operator.management.store": [],
    "corporation.business-operator.management.show": [
        {
            "name": "businessApplicationId"
        }
    ],
    "corporation.business-operator.management.info": [
        {
            "name": "businessApplicationId"
        }
    ],
    "corporation.business-operator.management.publish": [
        {
            "name": "businessApplicationId"
        },
        {
            "name": "businessId"
        }
    ],
    "corporation.media-check.index": [],
    "corporation.media-check.show": [
        {
            "name": "businessId"
        }
    ],
    "corporation.media-check.delete": [],
    "corporation.deposit-details.index": [],
    "corporation.deposit-details.business": [
        {
            "name": "requestId"
        }
    ],
    "corporation.deposit-details.staff": [
        {
            "name": "requestId"
        },
        {
            "name": "businessId"
        }
    ]
}
}
export {};
